### ISSUE TITLE
Code Coverage Instrumentation Failed At redEnvFactory

### ISSUE THREAD

**Issue by arcadeteddy** [salesforce/near-membrane#136]
Istanbul instruments all source code. Unfortunately, redEnvFactory is coerced to a string, it's missing a reference to the code coverage function that is in the outer scope. This causes an undefined access error when the red factory function is ran in the red realm. 

@jdalton

**Comment by jdalton** [comment]
We could put
```js
// istanbul ignore next
export const serializedRedEnvSourceText = (function redEnvFactory(blueEnv: MembraneBroker, hooks: MarshalHooks) {
```
To tell istanbul to not instrument that function. See [ignoring-code-for-coverage.md](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md#the-interface).

**Comment by rwaldron** [comment]
I think we can close this now that non-failing coverage has been introduced.
