### ISSUE TITLE
Question: Is it possible to use Child Realm in browser without access to browser-specific API?

### ISSUE THREAD

**Issue by mifopen** [salesforce/near-membrane#337]
It looks like the library fits our goals perfectly exhibiting identity continuity, preserving the integrity of the Incubator Realm. But we need our sandboxes to be as restricted by available API as possible. Actually we need a JS execution sandbox with ES-default intrinsics (nor browser neither node specific) + ability to provide some set of globals. Is it possible to achieve with this library? I have feeling that it should be by using `@locker/near-membrane-base` with some parts from `@locker/near-membrane-dom` but the lack of documentation makes reasoning quite hard.

**Comment by caridy** [comment]
@mifopen you got it correct. we don't have much documentation, but if people start using this, we can certainly work on that. the trick in near-membrane-dom is to create an iframe to extract the shape of the virtual environment from a newly created iframe, and the cache that shape. In your case, you must find another way to build the shape you need.

I realized that this issue wasn't reply for many weeks, apologies for that. did you find a solution for your question? do you need more help?

**Comment by caridy** [comment]
@jdalton can you provide more guidance on how to achieve this with the current API?
