### ISSUE TITLE
cache the browser/node descriptor maps and reference

### ISSUE THREAD

**Issue by caridy** [salesforce/near-membrane#36]
as today, every time you create a new env, the outer realm global object is inspected to extra all the info needed to build the sandbox, this information should be extracted during evaluation time rather than creation to avoid poisoning and other non-deterministic behavior.

the consumer of this package should be responsible for preparing the env before loading this package.

another alternative is to extra them once during the creation of the first sandbox, but that probably suffer from the same kind of problems.

The owner of the sandbox can also do extra mapping in case that the initial state of the outer realm is not exactly what they want, or they can attempt to create the proper distortion.

**Comment by caridy** [comment]
Now that we are caching the references of those object values that can't change over time, we need to figure how to handle the case of those that might be polyfilled, changed, or just plain new entries added to the global reference. We plan to keep this open until we make a determination, or we add an option to choose between cached globals vs recomputed globals when creating a new sandbox.

**Comment by jdalton** [comment]
This is now done :)
