### ISSUE TITLE
feature request: improve debug experience by set-up a private field on the proxy when possible

### ISSUE THREAD

**Issue by Jack-Works** [salesforce/near-membrane#386]
![image](https://user-images.githubusercontent.com/5390719/188431948-084793b5-971c-4719-8c63-2bdc9ac23e33.png)

This is possible when two realms can exchange objects. By setting a private field on it, we can improve the developer experience because they can know what is under this proxy.

This is also safe because the private field is not accessible outside the class body, if the class never read it, it is impossible to leak.

I have [implemented this feature](https://github.com/DimensionDev/aot-secure-ecmascript/commit/6cc8a567e25b223fd0d1ce35e7c40c8ebca15ad9) in my environment binding (where Node `vm` and Web `iframe` is both impossible), but I hope this feature can be in the upstream.

**Comment by jdalton** [comment]
Hi @Jack-Works!

Can you show what your output looks like when working with your patched code?  We've added support internally for custom console formatters. We could consider opening that up.

**Comment by Jack-Works** [comment]
I have a screenshot in the top thread. Custom console formatters are Chrome specific so it's less good than private fields IMO

**Comment by jdalton** [comment]
We have a `yarn build:dev` which adds more things to the proxy handler.
