### ISSUE TITLE
Question: `eval` vs `Function(code)()`

### ISSUE THREAD

**Issue by svallory** [salesforce/near-membrane#439]
I recently stumbled upon the `script-src: unsafe-eval` restriction in another project and got around it by using `Function(code)()` instead. 

I was wondering if you guys tried that route to remove that requirement and, if you don't mind, what problems have you encountered?

**Comment by Jack-Works** [comment]
If `Function(code)` can bypass `unsafe-eval`, your environment must have something wrong.

**Comment by svallory** [comment]
Lol! You are right, @Jack-Works!! I spent a lot of time in backend work and wasn't aware that `unsafe-eval` CSP blocked `Function(code)` too.

Since they don't work in the same way, and `Function` is a bit more secure, when it worked I simply thought "there must be an unsafe-function CSP`.

As it turns out, the tool was blocking the build by matching `eval(` with a regex or something. Even `globalThis['eval']()` works! HAHAHAHA I'm shocked. It's a pretty BIG player!

I'll submit a report there.
