### ISSUE TITLE
Proxy trap invariant gotchas

### ISSUE THREAD

**Issue by jdalton** [salesforce/near-membrane#7]
Something I've been bitten by in the past is the various proxy trap invariants that you have to be aware of when projecting one value in place of another. I ended up [with helpers](https://github.com/standard-things/esm/blob/868a9029e34ba3f57498736642b879d1671f499e/src/util/proxy-exports.js#L14-L16) like [`isUpdatableDescriptor`](https://github.com/standard-things/esm/blob/1b204dbc3d355a6126369e2ab5c7f4f31b7ee5a9/src/util/is-updatable-descriptor.js), [`isUpdatableGet`](https://github.com/standard-things/esm/blob/c2dc145b0e136baadafb4dc43b818c708bfeb8dc/src/util/is-updatable-get.js), and [`isUpdatableSet`](https://github.com/standard-things/esm/blob/c2dc145b0e136baadafb4dc43b818c708bfeb8dc/src/util/is-updatable-set.js).

This can rear up when projecting over non-configurable or frozen properties.

**Update:**

It looks like some of the traps always return `true` in places ([here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L169), [here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L221), [here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L227), [here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L233)) which could be a spot for an invariant to throw.

**Comment by jdalton** [comment]
It looks like some of the traps always return `true` in places ([here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L169), [here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L221), [here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L227), [here](https://github.com/caridy/secure-javascript-environment/blob/07591948ce5d9f2983019e37fa6e71d2610ee1f5/src/secure-proxy-handler.ts#L233)) which could be a spot for an invariant to throw.

**Comment by caridy** [comment]
Let's chat over this one, I'm not sure I understand the first part.

As for the second comment, those are explicit returns because if the control gets to the return statement is because the operation succeed on the shadow target, otherwise the invariant violation will happen on the shadow target itself. That might not be ideal because of the error stack, but the language invariant will be preserved I believe, let's chat about it.
